name: Build AC Server

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build & publish
        run: |
          dotnet publish \
            -c Release \
            -r linux-x64 \
            --self-contained true \
          
      - name: Copy publish output to build directory
        run: |
          mkdir -p /opt/ops/builds/ac-server
          rm -rf /opt/ops/builds/ac-server/*
          cp -r out-linux-x64/. /opt/ops/builds/ac-server/
